package com.example.chartapp

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import com.anychart.AnyChart
import com.anychart.AnyChartView
import com.anychart.chart.common.dataentry.SingleValueDataSet
import com.anychart.enums.Anchor
import com.anychart.graphics.vector.Fill
import com.anychart.graphics.vector.SolidFill
import com.anychart.graphics.vector.text.HAlign
import com.anychart.graphics.vector.text.VAlign

class CircularGaugeActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.circular_gauge)

        circularGauge(R.id.any_chart_view)
    }

     fun circularGauge(viewId: Int) {
        val anyChartView = findViewById<AnyChartView>(viewId)
        anyChartView.setProgressBar(findViewById(R.id.progress_bar))
        val circularGauge = AnyChart.circular()
        circularGauge.data(SingleValueDataSet(arrayOf("32", "34", "67", "93", "56", "100")))
        circularGauge.fill("#fff")
            .stroke(null)
            .padding(0.0, 0.0, 0.0, 0.0)
            .margin(100.0, 100.0, 100.0, 100.0)
        circularGauge.startAngle(0.0)
        circularGauge.sweepAngle(360.0)
        val xAxis = circularGauge.axis(0)
            .radius(100.0)
            .width(1.0)
            .fill(null as Fill?)
        xAxis.scale()
            .minimum(0.0)
            .maximum(100.0)
        xAxis.ticks("{ interval: 1 }")
            .minorTicks("{ interval: 1 }")
        xAxis.labels().enabled(false)
        xAxis.ticks().enabled(false)
        xAxis.minorTicks().enabled(false)
        circularGauge.label(0.0)
            .text("Temazepam, <span style=\"\">32%</span>")
            .useHtml(true)
            .hAlign(HAlign.CENTER)
            .vAlign(VAlign.MIDDLE)
        circularGauge.label(0.0)
            .anchor(Anchor.RIGHT_CENTER)
            .padding(0.0, 10.0, 0.0, 0.0)
            .height((17.0 / 2.0).toString() + "%")
            .offsetY(100.0.toString() + "%")
            .offsetX(0.0)
        val bar0 = circularGauge.bar(0.0)
        bar0.dataIndex(0.0)
        bar0.radius(100.0)
        bar0.width(17.0)
        bar0.fill(SolidFill("#64b5f6", 1.0))
        bar0.stroke(null)
        bar0.zIndex(5.0)
        val bar100 = circularGauge.bar(100.0)
        bar100.dataIndex(5.0)
        bar100.radius(100.0)
        bar100.width(17.0)
        bar100.fill(SolidFill("#F5F4F4", 1.0))
        bar100.stroke("1 #e5e4e4")
        bar100.zIndex(4.0)
        circularGauge.label(1.0)
            .text("Guaifenesin, <span style=\"\">34%</span>")
            .useHtml(true)
            .hAlign(HAlign.CENTER)
            .vAlign(VAlign.MIDDLE)
        circularGauge.label(1.0)
            .anchor(Anchor.RIGHT_CENTER)
            .padding(0.0, 10.0, 0.0, 0.0)
            .height((17.0 / 2.0).toString() + "%")
            .offsetY(80.0.toString() + "%")
            .offsetX(0.0)
        val bar1 = circularGauge.bar(1.0)
        bar1.dataIndex(1.0)
        bar1.radius(80.0)
        bar1.width(17.0)
        bar1.fill(SolidFill("#1976d2", 1.0))
        bar1.stroke(null)
        bar1.zIndex(5.0)
        val bar101 = circularGauge.bar(101.0)
        bar101.dataIndex(5.0)
        bar101.radius(80.0)
        bar101.width(17.0)
        bar101.fill(SolidFill("#F5F4F4", 1.0))
        bar101.stroke("1 #e5e4e4")
        bar101.zIndex(4.0)
        circularGauge.label(2.0)
            .text("Salicylic Acid, <span style=\"\">67%</span>")
            .useHtml(true)
            .hAlign(HAlign.CENTER)
            .vAlign(VAlign.MIDDLE)
        circularGauge.label(2.0)
            .anchor(Anchor.RIGHT_CENTER)
            .padding(0.0, 10.0, 0.0, 0.0)
            .height((17.0 / 2.0).toString() + "%")
            .offsetY(60.0.toString() + "%")
            .offsetX(0.0)
        val bar2 = circularGauge.bar(2.0)
        bar2.dataIndex(2.0)
        bar2.radius(60.0)
        bar2.width(17.0)
        bar2.fill(SolidFill("#ef6c00", 1.0))
        bar2.stroke(null)
        bar2.zIndex(5.0)
        val bar102 = circularGauge.bar(102.0)
        bar102.dataIndex(5.0)
        bar102.radius(60.0)
        bar102.width(17.0)
        bar102.fill(SolidFill("#F5F4F4", 1.0))
        bar102.stroke("1 #e5e4e4")
        bar102.zIndex(4.0)
        circularGauge.label(3.0)
            .text("Fluoride, <span style=\"\">93%</span>")
            .useHtml(true)
            .hAlign(HAlign.CENTER)
            .vAlign(VAlign.MIDDLE)
        circularGauge.label(3.0)
            .anchor(Anchor.RIGHT_CENTER)
            .padding(0.0, 10.0, 0.0, 0.0)
            .height((17.0 / 2.0).toString() + "%")
            .offsetY(40.0.toString() + "%")
            .offsetX(0.0)
        val bar3 = circularGauge.bar(3.0)
        bar3.dataIndex(3.0)
        bar3.radius(40.0)
        bar3.width(17.0)
        bar3.fill(SolidFill("#ffd54f", 1.0))
        bar3.stroke(null)
        bar3.zIndex(5.0)
        val bar103 = circularGauge.bar(103.0)
        bar103.dataIndex(5.0)
        bar103.radius(40.0)
        bar103.width(17.0)
        bar103.fill(SolidFill("#F5F4F4", 1.0))
        bar103.stroke("1 #e5e4e4")
        bar103.zIndex(4.0)
        circularGauge.label(4.0)
            .text("Zinc Oxide, <span style=\"\">56%</span>")
            .useHtml(true)
            .hAlign(HAlign.CENTER)
            .vAlign(VAlign.MIDDLE)
        circularGauge.label(4.0)
            .anchor(Anchor.RIGHT_CENTER)
            .padding(0.0, 10.0, 0.0, 0.0)
            .height((17.0 / 2.0).toString() + "%")
            .offsetY(20.0.toString() + "%")
            .offsetX(0.0)
        val bar4 = circularGauge.bar(4.0)
        bar4.dataIndex(4.0)
        bar4.radius(20.0)
        bar4.width(17.0)
        bar4.fill(SolidFill("#455a64", 1.0))
        bar4.stroke(null)
        bar4.zIndex(5.0)
        val bar104 = circularGauge.bar(104.0)
        bar104.dataIndex(5.0)
        bar104.radius(20.0)
        bar104.width(17.0)
        bar104.fill(SolidFill("#F5F4F4", 1.0))
        bar104.stroke("1 #e5e4e4")
        bar104.zIndex(4.0)
        circularGauge.margin(50.0, 50.0, 50.0, 50.0)
        circularGauge.title()
            .text(
                """Medicine manufacturing progress' +
        '<br/><span style="color:#929292; font-size: 12px;">(ACME CORPORATION)</span>"""
            )
            .useHtml(true)
        circularGauge.title().enabled(true)
        circularGauge.title().hAlign(HAlign.CENTER)
        circularGauge.title()
            .padding(0.0, 0.0, 0.0, 0.0)
            .margin(0.0, 0.0, 20.0, 0.0)
        anyChartView.setChart(circularGauge)
    }
}